#!/usr/bin/env bash
set -e

cmd=$1
shift

ec2_get_id () {
local name=$1
aws ec2 describe-instances --filters "Name=tag:Name,Values=$name" --query "Reservations[].Instances[].InstanceId" --output text
}

ec2_ls_csv  () {
    query='Reservations[].Instances[].[(Tags[?Key==`Name`].Value)[0] || `""`,
          InstanceId,
          State.Name,
          InstanceType,
          PrivateIpAddress,
          PublicIpAddress,
          SubnetId,
          BlockDeviceMappings[0].Ebs.VolumeId,
	  join(`;`, SecurityGroups[*].GroupId)
        ]'
    echo "Name,InstanceId,State,InstanceType,PrivateIpAddress,PublicIpAddress,SubnetId,VolumeId,SecurityGroupIds"
    aws ec2 describe-instances --query "$query" --output text | tr '\t' ','
}


case "$cmd" in
  ls)
    if [[ "$1" == "--csv" ]]; then
      ec2_ls_csv
    else
      ec2_ls_csv | column -s, -t
    fi
  ;;
  start) aws ec2 start-instances --instance-ids $(ec2_get_id "$1") ;;
  stop)  aws ec2  stop-instances --instance-ids $(ec2_get_id "$1") ;;

  sg_rules)
   COLS="GroupId,GroupName,Direction,Proto,Port,CidrIp,GroupId,Description"
   echo $COLS
   for x in `aws ec2 describe-security-groups --query 'SecurityGroups[].GroupId' | jq -r '.[] | @text' `; do
      aws ec2 describe-security-groups  --group-ids $x --query 'SecurityGroups[]' | jq -r '
  .[] |
  .GroupId as $gid |
  .GroupName as $name |
  ( [.IpPermissions[] + {"Direction": "Ingress"}] + [.IpPermissionsEgress[] + {"Direction": "Egress"}]) [] |
  .Direction as $direction |
  .IpProtocol as $proto |
  .ToPort as $port |
  ([.IpRanges[]] + [.UserIdGroupPairs[]])[] |
  [
    $gid,
    $name,
    $direction,
    $proto,
    $port,
    .CidrIp,
    .GroupId,
    .Description
  ] | @csv
'
   done
  ;;

  *)
    echo "ec2 commands:"
    echo "  ls         list instances"
    echo "  ls --csv   list instances as csv"
    echo "  ssh NAME"
    echo "  start NAME"
    echo "  stop NAME"
    echo "  sg_rules"
  ;;
esac
